### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with the collection of mathematical functions to operate on these data structures.

In [1]:
!pip install numpy

In [1]:
import numpy as np

## Creating arrays using numpy
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.shape)  # Shape of the array

(5,)


In [ ]:
arr2 = np.array([1, 3, 5, 6])
arr2.reshape(1, 4) ## 1 row and 4 columns

array([[1, 3, 5, 6]])

In [ ]:
## 2d array
arr3 = np.array([[1, 5, 6, 7, 1], [2, 6, 4, 0, 7]])
print(arr3)
print(arr3.shape)

[[1 5 6 7 1]
 [2 6 4 0 7]]
(2, 5)


In [3]:
np.arange(0, 6, 2)

array([0, 2, 4])

In [2]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [2]:
## numpy vectorized operations

arr4 = np.array([1, 2, 3, 4, 5])
arr5 = np.array([10, 56, 34, 78, 90])

print('Addition:', arr4 + arr5)

print('Subtraction:', arr4 - arr5)

print('Multiplication:', arr4 * arr5)

print('Division:', arr4 / arr5)

Addition: [11 58 37 82 95]
Subtraction: [ -9 -54 -31 -74 -85]
Multiplication: [ 10 112 102 312 450]
Division: [0.1        0.03571429 0.08823529 0.05128205 0.05555556]


In [3]:
## Universal functions (ufuncs)

arr6 = np.array([1, 4, 9, 16, 25])

print('Square root:', np.sqrt(arr6))
print('Exponential:', np.exp(arr6))
print('Sine', np.sin(arr6))
print('Cosine', np.cos(arr6))
print('Logarithm', np.log(arr6))

Square root: [1. 2. 3. 4. 5.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Sine [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Cosine [ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]
Logarithm [0.         1.38629436 2.19722458 2.77258872 3.21887582]


In [4]:
## Array slicing and indexing

arr7 = np.array([[2, 5, 7, 8], [4, 9, 10, 12], [1, 4, 8, 9]])
print(arr7)

[[ 2  5  7  8]
 [ 4  9 10 12]
 [ 1  4  8  9]]


In [5]:
arr7[0]

array([2, 5, 7, 8])

In [6]:
arr7[0, 4]

IndexError: index 4 is out of bounds for axis 1 with size 4

In [7]:
arr7[0, 3]

np.int64(8)

In [8]:
arr7[1:]

array([[ 4,  9, 10, 12],
       [ 1,  4,  8,  9]])

In [9]:
arr7[1:, 2:]

array([[10, 12],
       [ 8,  9]])

In [10]:
print(arr7[0 : 2, 1 : 3])

[[ 5  7]
 [ 9 10]]


In [13]:
## Modifying array elements

arr7[0, 0] = 87
print(arr7)

[[87 99 99 99]
 [ 4  9 10 12]
 [ 1  4  8  9]]


In [14]:
arr7[1:] = 100
print(arr7)

[[ 87  99  99  99]
 [100 100 100 100]
 [100 100 100 100]]


In [15]:
### Statistical concepts - Normalization and Standardization

## To have  a mean and standard deviation of 1, we can use the following code:

data = np.array([1, 2, 3 , 4, 5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean) / std_dev
print('Normalized data:', normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [16]:
## Mean , Median and Mode, Variance and Standard Deviation

data1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(data1)
print('Mean:', mean)
median = np.median(data1)
print('Median:', median)
mode = np.bincount(data1).argmax()
print('Mode:', mode)
variance = np.var(data1)
print('Variance:', variance)
std_dev = np.std(data1)
print('Standard Deviation:', std_dev)

Mean: 5.5
Median: 5.5
Mode: 1
Variance: 8.25
Standard Deviation: 2.8722813232690143


In [18]:
### Logical operations and boolean indexing

data3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data3[data3 > 5]

array([ 6,  7,  8,  9, 10])